version: '3.8'
name: clothesvirtualstore_deps

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_management               
    ports: 
      - 5672:5672
      - 15672:15672
    volumes:
      - /docker_conf/rabbitmq/data/:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    networks:
      - clothesvirtualstore_network
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: virtualstore
    networks:
      - clothesvirtualstore_network
  redis:
    image: redis
    command: redis-server --requirepass Redis2019!
    ports:
      - 6379:6379
    networks:
      - clothesvirtualstore_network
volumes:
    logs-folder:
        name: ${log_rabbitmq_management}
        driver: local
networks:
  clothesvirtualstore_network:
    name: clothesvirtualstore_network
    driver: bridge
